title: Arunava Chandan Roy
#logo: 
description: Hey there, I'm a data enthusiast who thrives on uncovering insights from numbers. I specialize in cleaning, analyzing, and visualizing data to empower businesses to make informed decisions. Check out my portfolio and let's team up to bring your data to life and drive success!
show_downloads: true
theme: slate-theme
